use_frameworks!

platform :ios, '10.0'

target 'FMFullscreenPopGesture_Example' do
  pod 'FMFullscreenPopGesture', :path => '../'

  target 'FMFullscreenPopGesture_Tests' do
    inherit! :search_paths

    
  end
end
